services:

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  db:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: exemplo
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-db:/var/lib/mysql